# GitHub Pages Configuration for MCP Conductor
title: MCP Conductor - MCP Testing Library
description: >-
  Comprehensive Node.js testing library for Model Context Protocol (MCP) servers.
  Features YAML declarative testing, programmatic JavaScript/TypeScript APIs and 
  advanced pattern matching.
url: "https://conductor.rhino-inquisitor.com"
baseurl: ""

# SEO and Social
author:
  name: Thomas Theunen
  email: thomas@example.com
  twitter: taurgis

twitter:
  username: taurgis
  card: summary_large_image

social:
  name: MCP Conductor
  links:
    - https://github.com/taurgis/mcp-conductor
    - https://www.npmjs.com/package/mcp-conductor

# Theme
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata

# Navigation
header_pages:
  - installation.md
  - quick-start.md
  - yaml-testing.md
  - programmatic-testing.md
  - pattern-matching.md
  - examples.md
  - api-reference.md
  - ai-agents.md
  - troubleshooting.md
  - development.md

# Social links
github_username: taurgis

# GitHub repository configuration
repository: taurgis/mcp-conductor
github:
  repository_url: "https://github.com/taurgis/mcp-conductor"
  repository_nwo: "taurgis/mcp-conductor"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - temp-testing/
  - test/
  - src/
  - bin/

# SEO Configuration
lang: en_US
timezone: UTC

# Feed
feed:
  posts_limit: 10
  excerpt_only: true
  
# Schema.org structured data
structured_data:
  type: "SoftwareApplication"
  applicationCategory: "DeveloperApplication"
  operatingSystem: "Cross-platform"
  softwareVersion: "1.0.3"
  downloadUrl: "https://www.npmjs.com/package/mcp-conductor"

# Keywords for SEO
keywords: >-
  Model Context Protocol, MCP, testing library, Node.js, JavaScript, TypeScript,
  protocol testing, JSON-RPC, stdio communication, AI agents, LLM tools,
  automated testing, server validation, API testing, pattern matching
